---
- name: Install Ruby RPM
  yum:
    name: "ruby-{{ ruby_version }}"
    state: present
    disablerepo: "*"
    enablerepo: "uclalib"

- name: Install/Update Base Ruby Gems
  command: >
    gem update --system
